### ISSUE TITLE
integration test example does not run

### ISSUE THREAD

**Issue by iguannago** [EthanRBrown/web-development-with-node-and-express-2e#14]
Hi Ethan, 

First of all, congratulation for your second edition of the book! 

Allow me to cut the chase, I have not been able to run this integration test you provide in the book: https://github.com/EthanRBrown/web-development-with-node-and-express-2e/blob/master/ch05/integration-tests/basic-navigation.test.js#L18 

The book does not explain how to run this test, by the way. It did not take long for me to read the puppeteer official documentation to find out that we should run it this way: node basic-navigation.test.js 

However, it fails with this: 
` node basic-navigation.test.js
/Users/davidcrespo/data/web-development-with-node-and-express/web-development-with-node-and-express-2e/ch05/integration-tests/basic-navigation.test.js:9
beforeEach(async () => {
^

ReferenceError: beforeEach is not defined
    at Object.<anonymous> (/Users/davidcrespo/data/web-development-with-node-and-express/web-development-with-node-and-express-2e/ch05/integration-tests/basic-navigation.test.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47`

It would be great if you could let me know what I am missing here. 

Kind regards, 
David

**Comment by EthanRBrown** [comment]
Hi, @iguannago...yes, I'm afraid I'm behind on a lot of the updates & maintenance for the repo.  I've really been struggling to meet all of my work and writing obligations, and I fear that updates to the book copy took precedence over repo work.  My apologies.  I've got a laundry list of things to do with the repo, but I'll start with this one...thanks for bringing it to my attention!

**Comment by iguannago** [comment]
Hi Ethan, 

Thanks for your quick response. 

Yes, I appreciate it is not a trivial task to bring up to date the book examples and the repo. It's just a bit disappointing, to be honest. I would have expected to find the material in O'Really up to date and in relatively good shape before making it available on the site for the customers like me. The O'Really subscription is not precisely a cheap one. Anyway, I guess this is not your fault and I should probably raise this complaint to O'Really itself. 

In any case, appreciate your response here. 

By the way, I could get the example working. 
I had to install the jest-puppeteer dependency as explained here: https://jestjs.io/docs/en/puppeteer#use-jest-puppeteer-preset
and then update the way the selector is passed to the page.click method. This line: `await Promise.all([page.waitForNavigation(), page.click('[data-test-id="about"]')])`

**Comment by EthanRBrown** [comment]
Oh, no, it's not O'Reilly's fault.  It's the author responsibility to maintain any source code repos -- ORA does not provide any assistance or support for that side of things, and they mostly just trust me to take care of it.  So I can't pass the bucks to the good folks at ORA here.  Having written a couple of books, I am somewhat regretting even having a companion repo, as it adds half again as much work as the considerably daunting effort of writing the book in the first place!

Anyway, I'm sorry to disappoint you, and I will redouble my efforts to get this into good shape.  I had some rather grandiose plans for the supplemental material in the repo...and I always tend to think big and underestimate how much time things will take.

**Comment by iguannago** [comment]
Ok, I see. Thanks for clarifying it. It does not fix the issue but at least it makes it more understandable :) 

I find the companion repo very useful, Ethan, if that is of any help. I have just completed until Chapter 6 so far and having the source helped me make good progress and understand things better. It definitely adds value to the book for me. 

Cheers, 
David

**Comment by EthanRBrown** [comment]
Hi, David,

I'm going to re-open this issue and fix it.  Thanks again for lighting a fire under me!

/e

**Comment by EthanRBrown** [comment]
Hi, David,

I see the problem now; you can't directly run (with Node) tests designed to be run by Jest (this is very common to the way most test frameworks work, with notable exceptions like Tape).

I do explain in the text how to correctly run these tests.  From Chapter 5:

> Before we move on, we need a way to run Jest (which will run any tests in our project). The conventional way to do that is to add a script to _package.json_. Edit _package.json_ (_ch05/package.json in the companion repo_), and modify the scripts property (or add it if it doesn’t exist):
> 
> ```json
> {
>   "scripts": {
>   "test": "jest"
> },
> ```
> 
> Now you can run all the tests in your project simply by typing that:
> 
> ```
> npm test
> ```

You could also run the test directly by typing `jest integration-tests/basic-navigation.test.js` (if you've installed Jest globally, which I don't recommend) or `./node_modules/.bin/jest integration-tests/basic-navigation.test.js`, but it's far easier for me to just run `npm test`.  You can also run `npm test -- --watch` (yes, that's two sets of dashes, a space, and then `--watch`), and it'll monitor the files and run the test when you do them.

So the repo wasn't in such bad shape as I thought!  Whew!  There's still work to do, though, so thanks for the prompt.

**Comment by EthanRBrown** [comment]
In case you're curious, the reason you can't directly run Jest tests directly (or Mocha or Jasmine, etc): these frameworks all inject globals that your scripts can use.  If you run them directly with Node, it doesn't know anything about those globals, which is why you were getting the failure `ReferenceError: beforeEach is not defined`).
