### ISSUE TITLE
Contact info if readers need help 

### ISSUE THREAD

**Issue by JackChristieVic** [EthanRBrown/web-development-with-node-and-express-2e#3]
Hi Ethan, is there an official way to contact you if we run into issues with our code when we code following your book?

**Comment by EthanRBrown** [comment]
Sure; you're welcome to email me at e@zepln.com.  The repo needs a lot
work...I was hoping to clean it up over the holidays, but there's so much
to do, oy!

**Comment by mrmadhat** [comment]
@JackChristieVic can't you raise your issue on this repo? That way other readers can not only help you (when they know the solution) but also benefit when they are stuck with the same issue 😄
