### ISSUE TITLE
Update lastRefresh property for the weather cache object

### ISSUE THREAD

**Issue by bytrangle** [EthanRBrown/web-development-with-node-and-express-2e#61]
I like the introduction of the concept of caching in chapter 19: Integrating with Third-Party APIs.

In the [module](https://github.com/EthanRBrown/web-development-with-node-and-express-2e/blob/master/ch18-19/lib/weather.js) for fetching weather data, I think the cache object should have its property `lastRefresh` updated after we call the weather API. Otherwise, the `lastRefresh` property will always have a value of 0, and we will always make an API request to the National Weather Service server.

The relevant code:
```js
module.exports = (locations) => {
  const cache = {
    refreshFrequency: 15 * 60 * 1000,
    lastRefreshed: 0,
    refreshing: false,
    forecasts: locations.map((location) => ({ location })),
  };
  const updateForecast = async (forecast) => {
    // ...
  }
  const getForecasts = async () => {
    if (Date.now() > cache.lastRefreshed + cache.refreshFrequency) {
      cache.refreshing = true;
      cache.forecasts = await Promise.all(cache.forecasts.map(updateForecast));
      cache.refreshing = false;
      // Should record the last time we call the weather API
      // Without this, the if statement above will always be satisfied.
      // cache.lastRefreshed = Date.now();
    } else {
      console.log('Last API request was less than 15 minutes ago');
    }
    return cache.forecasts;
  };
}
```
Besides, I like this pattern and I'd like to learn more about it. Does it have a name so that I can search for it? If not, what keywords can I use to search for it?

**Comment by EthanRBrown** [comment]
Hi, @bytrangle !  Thanks for catching this.  As to your question, I'm not sure there's a specific name for this technique...it's just a way to handle cache invalidation.  You might find some more information in the [cache invalidation](https://en.wikipedia.org/wiki/Cache_invalidation) page on Wikipedia.
