### ISSUE TITLE
Where is querystring parameter `redirect`?

### ISSUE THREAD

**Issue by bytrangle** [EthanRBrown/web-development-with-node-and-express-2e#62]
In chapter 18 - Authentication, inside the [authentication middleware](https://github.com/EthanRBrown/web-development-with-node-and-express-2e/blob/master/ch18-19/lib/auth.js), when someone visit the path `/auth/facebook` or `/auth/google`, we check to see if there is a querystring paramater named `redirect`.

```
lib/auth.js
// ...
app.get('/auth/facebook', (req, res, next) => {
  if(req.query.redirect) req.session.authRedirect = req.query.redirect
  passport.authenticate('facebook')(req, res, next)
})
```

But where is this parameter passed? I can't find any piece of code inside the repo that passes this `redirect` parameter.

**Comment by EthanRBrown** [comment]
Another good question, @bytrangle; I wish I had answered a year ago like a good author!  It looks like I had never made use of `req.query.redirect`; I might have planned to use that, but switched to a session property (`req.session.authRedirect`), or I was just using it for dev testing purposes.  I left it in there, but cleaned it up and made a comment to indicate that it's only there as a secondary mechanism.
