### ISSUE TITLE
an issue in ch03/02-meadowlark.js

### ISSUE THREAD

**Issue by seolog78** [EthanRBrown/web-development-with-node-and-express-2e#74]
Hello,

by node-start the script ch03/02-meadowlark.js I get an error:
C:\......\meadowlark.js:7
app.engine('handlebars', expressHandlebars({
                         ^

TypeError: expressHandlebars is not a function

But if I changed the 2nd line to 
const { engine } = require('express-handlebars')

and the 5th line to
app.engine('handlebars', engine({
  defaultLayout: 'main',
}))

respectively, if works as designed.

Regards,

**Comment by anchan42** [comment]
I think there are some breaking changes in the handlebar. If you use version 3.0.2 as in the repo, it should work fine.

**Comment by MUK94** [comment]
Thank you but I am still having this error
Error: ENOENT: no such file or directory, open 'E:\CODING\001-node-book\travel-site\app\views\layouts\main.handlebars'

here is my app.js file


`const express = require('express');
const {engine} = require('express-handlebars');

const app = express();
const port = process.env.PORT || 3000;

// Configure Handlebars view engine

app.engine('handlebars', engine({
  defaultLayout: 'main'
}))
app.set('view engine', 'handlebars')

app.get('/', (req, res) => res.render('home'));

app.get('/about', (req, res) => res.render('about'))

// CUSTOM 404 PAGE
app.use((req, res) => {
  res.status(404);
  res.render('404')
});

// CUSTOM 500 PAGE
app.use((err, req, res, next) => {
  console.error(err.message);
  res.status(500);
  res.render('500');
});

app.listen(port, () => console.log(`Express started on 127.0.0.1:${port};`));
`

**Comment by MUK94** [comment]
Need help please

**Comment by anchan42** [comment]
Maybe you can try to copy and paste the code from this repo and try to run it. If it runs, then there might be some errors in your setup. Double-check the directory name and file name to make sure also.

**Comment by MUK94** [comment]
Okay I will try it and see Thanks

**Comment by RuizeZ** [comment]
change app.engine('handlebars', expressHandlebars({}) to app.engine('handlebars', expressHandlebars.engine({}))

**Comment by lcy19** [comment]
> 

hi, there. I meet the same problem, and I find if I use `main.handlebars` rather than `main.hbs` as file name, it works well.

meadowlark.js
```js
const express = require('express')
const expressHandlebars = require('express-handlebars')

const app = express()
// add engine
app.engine('handlebars', expressHandlebars.engine({
  defaultLayout: 'main',
}))
app.set('view engine', 'handlebars')

const port = process.env.PORT || 4000

app.get('/', (req, res) => res.render('home'))
app.get('/about', (req, res) => res.render('about'))

// custom 404 page
app.use((req, res) => {
  res.status(404)
  res.render('404')
})

// custom 500 page
app.use((err, req, res, next) => {
  console.error(err.message)
  res.status(500)
  res.render('500')
})

app.listen(port, () => {
  console.log(
    `Express started on http://localhost:${port}; ` +
      'press Ctrl-C o terminate.'
  )
})

```

cause I'm fresh to express-handlebars, maybe there are other better ways, best wishes.

**Comment by Brivan-26** [comment]
According to the handlebars documentation, setting up the configuration is changed.
First:
`const {engine} = require('express-handlebars')`
Second:
`app.set('view engine', 'handlebars')`
`app.engine('handlebars', engine())`
If you want to overwrite default configs, you can work with the _create_ method:
```
const { create } = require('express-handlebars')
const hbs = create({
    defaultLayout: 'main_template'
});
app.engine('handlebars', hbs.engine)
```

For more information, check the installation guide: https://www.npmjs.com/package/express-handlebars

**Comment by EthanRBrown** [comment]
@seolog78, as other readers have noted (thank you @MUK94, @RuizeZ, and others, for providing prompt & correct explanations), when the book was published, `express-handlebars` 3.x was current.  Since then, the export signature for `express-handlebars` has changed.  I did add a comment to the source code that will hopefully clear up any confusion that readers have.  Sorry about the woefully late response to this.
